config/routes.rb
Rails.application.routes.draw do
  get 'email/index'
  get 'email/send'
  get 'province/name'
  get 'user/index'
  devise_for :customers
  devise_for :users
  get 'cart/add_to_cart'
  get 'cart/remove_from_cart'
  get 'cart/update_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'search/index'
  get 'categories/index'
  get 'categories/list'
  get 'products/index'
  get 'products/show'
  get 'products/cart'
  post 'carts/add_item'
  post 'carts/remove_item'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
  get '/Products/index', to:'products#index'
  get '/Products/show', to:'products#show'
  get '/Products/cart', to:'cart#show'
  get '/Products/cartRemove', to:'products#cartRemove'
  get '/Categories/index', to:'categories#index'
  get '/Categories/list', to:'categories#list'
  get '/Search/result', to:'search#index'
  get '/account', to:'user#index'
  get '/Contact', to:'home#show'
  patch '/update', to: 'user#update', as: 'update'
  get '/users/sign_out', to:'user#sign_out'
  post '/purchase', to: 'invoice#index', as: 'purchase'
  post '/send', to: 'email#send', as: 'send'

  # post '/add_to_cart', to: 'cart#add_to_cart'
  get '/view_cart', to: 'cart#view_cart'
  delete '/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  post '/add_to_cart', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_cart/:id', to: 'cart#update_cart', as: 'update_cart'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at] # Add any additional searchable attributes here
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :delete_all
  
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    column_names
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
    
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "id_value", "phone", "updated_at"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :order
  has_one_attached :avatar
  validates :email, presence: true, uniqueness: true
end

app/models/home.rb
class Home < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "heading", "id", "id_value", "message_one", "message_one_heading", "message_two", "message_two_heading", "moto", "updated_at"]
      end
    
end

app/models/order.rb
class Order < ApplicationRecord
  # Associations
  belongs_to :customer

  # Validations
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :gst, :hst, :pst, numericality: { greater_than_or_equal_to: 0 }
  validates :address, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["customer"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "customer_id", "email", "gst", "hst", "id", "id_value", "order_item", "pst", "updated_at"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    # Associations
    belongs_to :order
    belongs_to :product
  
    # Validations
    validates :order_id, presence: true
    validates :product_id, presence: true
    validates :Quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  end
  

app/models/product.rb
class Product < ApplicationRecord
  # Associations
  belongs_to :category
  has_many :order_items, dependent: :delete_all

  # Validations
  validates :name, presence: true
  validates :price, presence: true, numericality: { message: 'must be numeric' }
  validates :description, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["category", "order_items"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "name", "price", "updated_at"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  # Validations
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst", "hst", "id", "id_value", "name", "pst", "updated_at"]
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_secure_password
    has_many :orders, dependent: :delete_all
  end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_customer!
  def add_to_cart
    session[:cart] ||= {}
    product_id = params[:product_id]
    session[:cart][product_id] ||= 0
    session[:cart][product_id] += 1
    redirect_to view_cart_path, notice: 'Product added to cart successfully'

  end

  def remove_from_cart
      product_id = params[:id]
      session[:cart].delete(product_id)
      redirect_to view_cart_path, notice: 'Product removed from cart successfully'
  end

  def update_cart
      product_id = params[:product_id]
      quantity = params[:quantity][product_id].to_i
      session[:cart][product_id] = quantity if session[:cart][product_id].present?
      redirect_to view_cart_path, notice: 'Cart updated successfully'
  end
   
   
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
      @products = Product.find(session[:cart])
    end
  
    def add_item
      session[:cart] ||= []
      product_id = params[:product_id].to_i
      session[:cart] << product_id unless session[:cart].include?(product_id)
    end
      
  
    def remove_item
      product_id = params[:product_id].to_i
      session[:cart].delete(product_id)
      redirect_back(fallback_location: root_path)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/remove_from_cart.html.erb
<h1>Cart#remove_from_cart</h1>
<p>Find me in app/views/cart/remove_from_cart.html.erb</p>

app/views/cart/update_cart.html.erb
<h1>Cart#update_cart</h1>
<p>Find me in app/views/cart/update_cart.html.erb</p>

app/views/cart/view_cart.html.erb
<div class="container">
    <h1 class="text-center mt-4 mb-4">Shopping Cart</h1>
    <% if session[:cart].present? %>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Product Name</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <% session[:cart].each do |product_id, quantity| %>
            <tr>
                <% product = Product.find(product_id) %>
                <td><%= product.name %></td>
                <% if product.sale %>
                  <% discounted_price = product.price * 0.7 * quantity %> <!-- Deduct 30% for sale -->
                  <td><%= number_to_currency(discounted_price) %></td>
                <% else %>
                  <td><%= number_to_currency(product.price * quantity) %></td>
                <% end %>
                <td>
                    <%= form_tag update_cart_path(product_id), method: :patch, class: "form-inline" do %>
                        <%= hidden_field_tag :product_id, product_id %>
                        <%= number_field_tag "quantity[#{product_id}]", quantity, class: "form-control mr-2", id: "quantity_#{product_id}" %>
                        <%= submit_tag "Update", class: "btn btn-primary btn-sm" %>
                    <% end %>
                </td>
                <td>
                    <%= button_to "Remove", remove_from_cart_path(product_id), method: :delete, class: "btn btn-danger btn-sm" %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <% else %>
    <div class="alert alert-info mt-4" role="alert">
        Your shopping cart is empty.
    </div>
    <% end %>
</div>

app/views/carts/show.html.erb
<h1><%= count = 0 %></h1>
<h1><%= debug session[:cart] %></h1>

<div class="card">
  <div class="card-body">
    <% @products.each do |product| %>
      <div class="row">
        <div class="col-6">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text">Quantity: <%= %></p>
          <p class="card-text">Price: <%= number_to_currency(product.price) %></p>
        </div>
        <div class="col-3">  
            <a class=" btn btn-danger" href="/Products/cartRemove?product_id=<%= product.id %>" >Remove Item</a>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
</div>