config/routes.rb
Rails.application.routes.draw do
  get 'email/index'
  get 'email/send'
  get 'province/name'
  get 'user/index'
  devise_for :customers
  devise_for :users
  get 'cart/add_to_cart'
  get 'cart/remove_from_cart'
  get 'cart/update_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'search/index'
  get 'categories/index'
  get 'categories/list'
  get 'products/index'
  get 'products/show'
  get 'products/cart'
  post 'carts/add_item'
  post 'carts/remove_item'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
  get '/Products/index', to:'products#index'
  get '/Products/show', to:'products#show'
  get '/Products/cart', to:'cart#show'
  get '/Products/cartRemove', to:'products#cartRemove'
  get '/Categories/index', to:'categories#index'
  get '/Categories/list', to:'categories#list'
  get '/Search/result', to:'search#index'
  get '/account', to:'user#index'
  get '/Contact', to:'home#show'
  patch '/update', to: 'user#update', as: 'update'
  get '/users/sign_out', to:'user#sign_out'
  post '/purchase', to: 'invoice#index', as: 'purchase'
  post '/send', to: 'email#send', as: 'send'

  # post '/add_to_cart', to: 'cart#add_to_cart'
  get '/view_cart', to: 'cart#view_cart'
  delete '/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  post '/add_to_cart', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_cart/:id', to: 'cart#update_cart', as: 'update_cart'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at] # Add any additional searchable attributes here
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :delete_all
  
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    column_names
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
    
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "id_value", "phone", "updated_at"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :order
  has_one_attached :avatar
  validates :email, presence: true, uniqueness: true
end

app/models/home.rb
class Home < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "heading", "id", "id_value", "message_one", "message_one_heading", "message_two", "message_two_heading", "moto", "updated_at"]
      end
    
end

app/models/order.rb
class Order < ApplicationRecord
  # Associations
  belongs_to :customer

  # Validations
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :gst, :hst, :pst, numericality: { greater_than_or_equal_to: 0 }
  validates :address, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["customer"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "customer_id", "email", "gst", "hst", "id", "id_value", "order_item", "pst", "updated_at"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    # Associations
    belongs_to :order
    belongs_to :product
  
    # Validations
    validates :order_id, presence: true
    validates :product_id, presence: true
    validates :Quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  end
  

app/models/product.rb
class Product < ApplicationRecord
  # Associations
  belongs_to :category
  has_many :order_items, dependent: :delete_all

  # Validations
  validates :name, presence: true
  validates :price, presence: true, numericality: { message: 'must be numeric' }
  validates :description, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["category", "order_items"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "name", "price", "updated_at"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  # Validations
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst", "hst", "id", "id_value", "name", "pst", "updated_at"]
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_secure_password
    has_many :orders, dependent: :delete_all
  end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_customer!
  def index
    @user = Customer.find(current_customer.id)
    @orders = Order.where(customer_id: current_customer.id)
  
    @order_items = {}
    @orders.each do |order|
      order_items = OrderItem.where(order_id: order.id)
      items_with_quantity = []
  
      order_items.each do |order_item|
        product = Product.find(order_item.product_id)
        items_with_quantity << { product: product, quantity: order_item.Quantity }
      end
  
      @order_items[order.id] = items_with_quantity
    end
  end
  
  
  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      # Update successful, handle accordingly (e.g., redirect to another page)
      redirect_to '/account', notice: 'Customer information updated successfully.'
    else
      # Update failed, render the edit page again with error messages
      render :edit
    end
  end

  def sign_out
    reset_session
    redirect_to '/', notice: 'Customer information updated successfully.'
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :address, :province_id, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card shadow">
        <h3 class="card-header bg-primary text-white">
          User Information
        </h3>
        <div class="card-body">
          <div class="text-center">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, class: "avatar img-fluid rounded-circle mb-3", style: "width: 100px; height: 100px;" %>
            <% else %>
              <img src="default_avatar.png" class="avatar img-fluid rounded-circle mb-3" style="width: 100px; height: 100px;" alt="Default Avatar">
            <% end %>
          </div>
          <form>
            <div class="form-group">
              <label for="email">Email address</label>
              <input type="address" class="form-control" id="email" value=<%= @user.email %> disabled>
            </div>
            <div class="form-group">
              <label for="address">Address</label>
              <% if @user.address.nil? %>
                <input type="string" class="form-control" id="address" value="Not added yet" disabled>
              <% else %>
                <input type="string" class="form-control" id="address" value="<%= @user.address %>" disabled>
              <% end %>
            </div>
            <div class="form-group">
              <label for="province">Province</label>
              <% if @user.province_id.nil? %>
                <input type="province" class="form-control" id="province" value="Not added yet" disabled>
              <% else %>
                <input type="province" class="form-control" id="province" value="<%= Province.find(@user.province_id).name %>" disabled>
              <% end %>
            </div>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editModal">
              Edit Account
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
  <h1>Orders</h1>
  <% count = 0 %>
  <% @orders.each do |order| %>
    <div class="card mb-3">
      <div class="card-body">
        <h2 class="card-title">Sr: <%= count += 1 %></h2>
        <p class="card-text">Email: <%= order.email %></p>
        <p class="card-text">Address: <%= order.address %></p>
        
        <h3 class="card-subtitle mb-2 text-muted">Order Items:</h3>
        <ul class="list-group">
          <% total_price = 0 %>
          <% @order_items[order.id].each do |item| %>
            <li class="list-group-item"><%= item[:product].name %> - Quantity: <%= item[:quantity] %> - <%= item[:product].price * item[:quantity]%></li> <% total_price += item[:product].price * item[:quantity] %>
          <% end %>
        </ul>
        <div class="invoice-total mt-3">
            <p><strong>Subtotal:</strong> <%= number_to_currency(total_price) %></p>
            <p><strong>GST (<%= order.gst %>%) :</strong> <%= number_to_currency(total_price *  order.gst/100) %></p>
            <p><strong>PST (<%= order.pst %>%):</strong> <%= number_to_currency(total_price *  order.pst/100 )%></p>
            <p><strong>HST (<%=  order.hst %>%):</strong> <%= number_to_currency(total_price *  order.hst/100)%></p>
            <hr>
            <p><strong>Total:</strong> <%= number_to_currency(total_price + (total_price * order.gst/100) + (total_price * order.pst/100) + (total_price * order.hst/100)) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Account</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @user, url: update_path, method: :patch do |f| %>
          <%= hidden_field_tag :id, @user.id %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :avatar %>
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :province_id %>
            <%= f.collection_select :province_id, Province.all, :id, :name, { prompt: "Select province" }, class: 'form-control' %>
          </div>
          <!-- Add other form fields as needed -->
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Save changes", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>