config/routes.rb
Rails.application.routes.draw do
  get 'email/index'
  get 'email/send'
  get 'province/name'
  get 'user/index'
  devise_for :customers
  devise_for :users
  get 'cart/add_to_cart'
  get 'cart/remove_from_cart'
  get 'cart/update_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'search/index'
  get 'categories/index'
  get 'categories/list'
  get 'products/index'
  get 'products/show'
  get 'products/cart'
  post 'carts/add_item'
  post 'carts/remove_item'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
  get '/Products/index', to:'products#index'
  get '/Products/show', to:'products#show'
  get '/Products/cart', to:'cart#show'
  get '/Products/cartRemove', to:'products#cartRemove'
  get '/Categories/index', to:'categories#index'
  get '/Categories/list', to:'categories#list'
  get '/Search/result', to:'search#index'
  get '/account', to:'user#index'
  get '/Contact', to:'home#show'
  patch '/update', to: 'user#update', as: 'update'
  get '/users/sign_out', to:'user#sign_out'
  post '/purchase', to: 'invoice#index', as: 'purchase'
  post '/send', to: 'email#send', as: 'send'

  # post '/add_to_cart', to: 'cart#add_to_cart'
  get '/view_cart', to: 'cart#view_cart'
  delete '/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  post '/add_to_cart', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_cart/:id', to: 'cart#update_cart', as: 'update_cart'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at] # Add any additional searchable attributes here
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :delete_all
  
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    column_names
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
    
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "id_value", "phone", "updated_at"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :order
  has_one_attached :avatar
  validates :email, presence: true, uniqueness: true
end

app/models/home.rb
class Home < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "heading", "id", "id_value", "message_one", "message_one_heading", "message_two", "message_two_heading", "moto", "updated_at"]
      end
    
end

app/models/order.rb
class Order < ApplicationRecord
  # Associations
  belongs_to :customer

  # Validations
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :gst, :hst, :pst, numericality: { greater_than_or_equal_to: 0 }
  validates :address, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["customer"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "customer_id", "email", "gst", "hst", "id", "id_value", "order_item", "pst", "updated_at"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    # Associations
    belongs_to :order
    belongs_to :product
  
    # Validations
    validates :order_id, presence: true
    validates :product_id, presence: true
    validates :Quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  end
  

app/models/product.rb
class Product < ApplicationRecord
  # Associations
  belongs_to :category
  has_many :order_items, dependent: :delete_all

  # Validations
  validates :name, presence: true
  validates :price, presence: true, numericality: { message: 'must be numeric' }
  validates :description, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["category", "order_items"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "name", "price", "updated_at"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  # Validations
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst", "hst", "id", "id_value", "name", "pst", "updated_at"]
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_secure_password
    has_many :orders, dependent: :delete_all
  end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def list
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/index.html.erb
<div class='container'>
    <h1>All Categories</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td><a href="/Categories/list?id=<%= category.id %>">View Products</a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/categories/list.html.erb
<div class='container'>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4">
        <div class="card h-100 shadow-sm">
          <div class="card-body d-flex flex-column justify-content-between Products">
            <h5 class="card-title"><%= product.name %></h5>
            <% if product.sale %>
              <% discounted_price = product.price * 0.7 %> <!-- Deduct 30% for sale -->
              <p class="card-text"><strong>Price:</strong> <del><%= number_to_currency(product.price) %></del> <%= number_to_currency(discounted_price) %></p>
              <p class="card-text">On Sale</p>
            <% else %>
              <p class="card-text"><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
              <p class="card-text">Not on Sale</p>
            <% end %>
            <!-- Add more product details as needed -->
            <div class="mt-auto">
              <a href="/Products/show?id=<%= product.id %>" class="btn btn-primary btn-block">View Details</a>
              <%= button_to "Add to Cart", add_to_cart_path(product_id: product.id), method: :post, remote: true, class: "btn btn-primary", form_class: "form-inline", params: { redirect_path: view_cart_path } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>