config/routes.rb
Rails.application.routes.draw do
  get 'email/index'
  get 'email/send'
  get 'province/name'
  get 'user/index'
  devise_for :customers
  devise_for :users
  get 'cart/add_to_cart'
  get 'cart/remove_from_cart'
  get 'cart/update_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'search/index'
  get 'categories/index'
  get 'categories/list'
  get 'products/index'
  get 'products/show'
  get 'products/cart'
  post 'carts/add_item'
  post 'carts/remove_item'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
  get '/Products/index', to:'products#index'
  get '/Products/show', to:'products#show'
  get '/Products/cart', to:'cart#show'
  get '/Products/cartRemove', to:'products#cartRemove'
  get '/Categories/index', to:'categories#index'
  get '/Categories/list', to:'categories#list'
  get '/Search/result', to:'search#index'
  get '/account', to:'user#index'
  get '/Contact', to:'home#show'
  patch '/update', to: 'user#update', as: 'update'
  get '/users/sign_out', to:'user#sign_out'
  post '/purchase', to: 'invoice#index', as: 'purchase'
  post '/send', to: 'email#send', as: 'send'

  # post '/add_to_cart', to: 'cart#add_to_cart'
  get '/view_cart', to: 'cart#view_cart'
  delete '/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  post '/add_to_cart', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_cart/:id', to: 'cart#update_cart', as: 'update_cart'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at] # Add any additional searchable attributes here
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :delete_all
  
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    column_names
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
    
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "id_value", "phone", "updated_at"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :order
  has_one_attached :avatar
  validates :email, presence: true, uniqueness: true
end

app/models/home.rb
class Home < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "heading", "id", "id_value", "message_one", "message_one_heading", "message_two", "message_two_heading", "moto", "updated_at"]
      end
    
end

app/models/order.rb
class Order < ApplicationRecord
  # Associations
  belongs_to :customer

  # Validations
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :gst, :hst, :pst, numericality: { greater_than_or_equal_to: 0 }
  validates :address, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["customer"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "customer_id", "email", "gst", "hst", "id", "id_value", "order_item", "pst", "updated_at"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    # Associations
    belongs_to :order
    belongs_to :product
  
    # Validations
    validates :order_id, presence: true
    validates :product_id, presence: true
    validates :Quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  end
  

app/models/product.rb
class Product < ApplicationRecord
  # Associations
  belongs_to :category
  has_many :order_items, dependent: :delete_all

  # Validations
  validates :name, presence: true
  validates :price, presence: true, numericality: { message: 'must be numeric' }
  validates :description, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["category", "order_items"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "name", "price", "updated_at"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  # Validations
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst", "hst", "id", "id_value", "name", "pst", "updated_at"]
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_secure_password
    has_many :orders, dependent: :delete_all
  end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Application</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.5.1.slim.min.js' %>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js' %>
  <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag 'css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <style>
   
  </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav mr-auto">
      <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/Products/index">Products</a>
      <a class="nav-item nav-link" href="/Categories/index">Categories</a>
      <a class="nav-item nav-link" href="/admin">Admin</a>
      <a class="nav-item nav-link" href="/view_cart">Cart</a>
      <a class="nav-item nav-link" href="/Contact">Contact</a>
      <a class="nav-item nav-link" href="/account">Account</a>
      <a class="nav-item nav-link" href="/account">Account</a>
      <% if customer_signed_in? %>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %></li>
      <% end %>
    </div>
    <form class="form-inline my-2 my-lg-0" action='/Search/result' method='get'>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='search'>
      <select class="custom-select mr-sm-2" name='category'>
        <option selected value='all'>All Categories</option>
        <% Category.all.each do |category| %>
          <option value="<%= category.id %>"><%= category.name %></option>
        <% end %>
      </select>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
  <%= yield %>
</body>
</html>